### ISSUE TITLE
recent-contributions NullPointerException

### ISSUE THREAD

**Issue by pavlikovskiy** [pavlikovskiy/coinshome.net#47]
URL: http://www.coinshome.net/ccc/recent-contributions.htm?pagingNumberPer_cvl=20&pagingPage_cvl=6&action=pending_revision_list&sortDirection_cvl=1&

java.lang.NullPointerException at org.apache.jsp.WEB_002dINF.jsp.gallery.ccc.mgr.coin_005frevision_005flist_jsp._jspService(coin_005frevision_005flist_jsp.java:1736) at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) at javax.servlet.http.HttpServlet.service(HttpServlet.java:717) at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:374) at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:342) at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:267) at javax.servlet.http.HttpServlet.service(HttpServlet.java:717) at

**Comment by pavlikovskiy** [comment]
done
